<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	  
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>True</PublishAot>
    <SignAssembly>False</SignAssembly>
    <DelaySign>True</DelaySign>
    <Title>Dita</Title>
    <Company>Afrowave</Company>
    <Description>Disk testing software client</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <FileAlignment>4096</FileAlignment>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
    <FileAlignment>4096</FileAlignment>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Tmds.DBus.Protocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dita.Gui\Dita.Gui.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <TrimmerRootDescriptor Include="..\rd.xml" />
  </ItemGroup>
</Project>
