<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Identity\Models\" />
    <Folder Include="Mailer\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Afrowave.SharedTools.Api" Version="0.0.3" />
    <PackageReference Include="Afrowave.SharedTools.Models" Version="1.4.0-alpha" />
    <PackageReference Include="MailKit" Version="4.15.1" />
  </ItemGroup>

</Project>
