<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>

	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dita.Gui\Dita.Gui.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <TrimmerRootDescriptor Include="..\rd.xml" />
  </ItemGroup>
</Project>
